version: "3"

services:
  db:
    image: mysql:latest
    container_name:  MySql_DataBase
    ports:
    - "33006:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: Project_parts_DB
